# Generated by Django 3.2.7 on 2023-05-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0006_alter_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='precio',
            field=models.FloatField(null=True, verbose_name='precio'),
        ),
    ]
