# Generated by Django 3.2.7 on 2023-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0008_alter_project_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='precio',
            field=models.FloatField(null=True, verbose_name='precio'),
        ),
    ]
