# Generated by Django 3.2.7 on 2023-05-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0014_auto_20230513_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='redes',
        ),
    ]
