# Generated by Django 3.2.7 on 2023-05-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='redes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('link_redes1', models.URLField(blank=True, null=True, verbose_name='Direcciones Redes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizado')),
            ],
            options={
                'verbose_name': 'Redes',
                'verbose_name_plural': 'Redes',
                'ordering': ['-created'],
            },
        ),
    ]
