# Generated by Django 3.2.7 on 2023-05-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='redes',
        ),
    ]
