# Generated by Django 3.2.7 on 2023-05-19 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230519_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='redes',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion'),
        ),
    ]
