# Generated by Django 3.2.7 on 2023-05-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_redes_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='redes',
        ),
    ]
