# Generated by Django 3.2.7 on 2023-05-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contenidos_empresa',
        ),
    ]
