# Generated by Django 3.2.7 on 2023-05-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_contenidos_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenidos_empresa',
            old_name='contenido_mision',
            new_name='contenido',
        ),
        migrations.RemoveField(
            model_name='contenidos_empresa',
            name='contenido_vision',
        ),
    ]
