# Generated by Django 3.2.7 on 2023-06-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_contenidos_empresa_contenido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contenidos_empresa',
            new_name='empresa',
        ),
    ]
